### ISSUE TITLE
[BUG]: fixed github icon in footer

### ISSUE THREAD

**Issue by Ananya2001-an** [Ananya2001-an/note#4]
**Describe the bug**
The Github icon link in footer has fixed position right now but I want that to be removed.

**Expected behavior**
 I want it to be at the bottom of the page depending upon screen height but not fixed position.

**Screenshot**
![image](https://user-images.githubusercontent.com/55504616/218473363-32e601f7-6fe3-4eba-9043-fa24a7ecf593.png)

**Additional context**

**Comment by msboffl** [comment]
Hi, @Ananya2001-an 
I would like to contribute this this issue.

**Comment by msboffl** [comment]
Hi @Ananya2001-an please review the PR

**Comment by msboffl** [comment]
@Ananya2001-an Close this issue
